runtime: python38
entrypoint: gunicorn -b :$PORT lmnop_project.wsgi

handlers:
- url: /static
  static_dir: www/static/

- url: /.*
  script: auto

env_variables:
  LMNOP_DB_PW: Passw0rd

beta_settings:
  cloud_sql_instances: lmnop-271010:us-central1:lmnop