# Generated by Django 2.1.11 on 2020-05-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_auto_20200505_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
