# Generated by Django 2.1.11 on 2020-05-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_auto_20200421_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='ages',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='time',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='url',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
