# Generated by Django 2.1.11 on 2020-05-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0003_auto_20200509_2246'),
        ('lmn', '0003_auto_20200508_1722'),
    ]

    operations = [
    ]
