# Generated by Django 2.1.11 on 2020-05-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0003_auto_20200508_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
