# Generated by Django 2.1.11 on 2020-05-09 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0005_auto_20200508_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
