# Generated by Django 2.1.11 on 2020-05-10 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0008_auto_20200509_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
