# Generated by Django 2.1.11 on 2020-05-10 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0012_auto_20200510_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uprofile',
            old_name='profilePicture',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='birthday',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='city',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='description',
            field=models.TextField(default=1, max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='favoriteArtist',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='favoriteVenue',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='state',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
