# Generated by Django 2.1.11 on 2020-05-11 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0015_auto_20200510_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='birthday',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='favoriteArtist',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='favoriteVenue',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
