# Generated by Django 2.1.11 on 2020-05-11 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0016_auto_20200511_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
