# Generated by Django 2.1.11 on 2020-05-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0020_auto_20200511_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
